</br>


```{r include=F, eval=T , echo=F}
library(crosstalk)
library(knitr)
library(kableExtra)
library(DT)
library(dplyr)
library(webshot)
library(leaflet)
#https://rstudio.github.io/DT/functions.html

```

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 10000)
```

## 2018/19 NCAAB Team Rankings

```{r results="asis", echo=F, }
#this was a bitch to figure out how to print..
#https://stackoverflow.com/questions/33179856/how-to-increase-header-font-size-and-remove-square-bracket-from-output
cat("<h4>",paste0( "Last Updated: ", Sys.time(), " EST"), "</h4>\n")
```
---


```{r results="asis", echo=F}


proj<-read.csv("~/NCAA/ncaa-preseason/Team Projections/teamprojections.csv", stringsAsFactors = F)
rows<-nrow(proj) #store length, gets screwed up once coverting to SharedData

# Wrap data frame in SharedData
proj <- SharedData$new(proj)

# Create a filter input
bscols(widths = 3,
       filter_select(id="Conf", label="Conference", sharedData = proj, ~Conf, multiple = F)
)
proj%>%
  datatable(rownames = F, options = list(dom = '', ordering=F, pageLength=rows),caption = htmltools::tags$caption(
    style = 'caption-side: bottom; text-align: left;',
    paste0('2018/19 Predictions."LastKPOMRk" = 17/18 End of Season KenPom Rank')
  ))%>%
  formatStyle( 0, target= 'row',color = 'black', fontSize="110%", lineHeight="75%") %>%
  formatRound(columns = 3, digits =3)


```


